apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-cluster-issuer
  namespace: cert-manager
spec:
  vault:
    server: https://vault.vault.svc.cluster.local:8200
    path: pki_int/sign/calm-role
    caBundleSecretRef:
      key: ca.crt
      name: vault-tls-final
    clientCertSecretRef:
      key: tls.crt
      name: vault-tls-final
    clientKeySecretRef:
      key: tls.key
      name: vault-tls-final
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: cert-manager-role
        serviceAccountRef:
          name: cert-manager
