apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: vault
spec:
  secretName: vault-tls
  dnsNames:
    - vault.calmhlynn.com
  issuerRef:
    name: letsencrypt-prod-dns01
    kind: ClusterIssuer
