apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: vault
spec:
  secretName: vault-tls
  dnsNames:
    - vault.vault.svc.cluster.local
  issuerRef:
    name: vault-cluster-issuer
    kind: ClusterIssuer
