apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-rs
  namespace: gateway
spec:
  secretName: app1-tls
  dnsNames:
    - calmhlynn.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
