global:
  enabled: true

server:
  affinity: ""

  volumes:
    - name: tls
      # secret:
      #   secretName: vault-tls
  volumeMounts:
    - name: tls
      mountPath: /vault/userconfig/tls
      readOnly: true

  ha:
    enabled: true

    raft:
      enabled: true
      setNodeId: true
      config: |
        storage "raft" {
          path = "/vault/data"
        }

        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_disable = "true"
        }
        service_registration "kubernetes" {}

injector:
  enabled: true
