global:
  enabled: true
  tlsDisable: false

server:
  extraEnvironmentVars:
    # VAULT_TLSCERT: /vault/userconfig/tls/tls.crt
    # VAULT_TLSKEY: /vault/userconfig/tls/tls.key
    VAULT_CACERT: /vault/userconfig/tls/ca.crt
    VAULT_TLSCERT: /vault/userconfig/tls/tls.crt
    VAULT_TLSKEY: /vault/userconfig/tls/tls.key

  volumes:
    - name: tls
      secret:
        defaultMode: 420
        secretName: vault-tls-final

  volumeMounts:
    - mountPath: /vault/userconfig/tls
      name: tls
      readOnly: true

  standalone:
    enabled: false

  affinity: ""
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true
      config: |
        cluster_name = "vault-integrated-storage"

        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_cert_file = "/vault/userconfig/tls/ca.crt"
          tls_key_file  = "/vault/userconfig/tls/tls.key"
          tls_client_ca_file = "/vault/userconfig/tls/tls.crt"
        }
        storage "raft" {
          path = "/vault/data"
        }
        disable_mlock = true
        service_registration "kubernetes" {}

  # ingress:
  #   enabled: true
  #   annotations:
  #     kubernetes.io/ingress.class: "nginx"
  #     cert-manager.io/cluster-issuer: "letsencrypt-prod-dns01"
  #   ingressClassName: "nginx"        
  #   pathType: Prefix            
  #   activeService: true         
  #   hosts:
  #     - host: vault.calmhlynn.com
  #       paths:
  #         - "/"
  #   tls:
  #     - secretName: vault-tls
  #       hosts:
  #         - vault.calmhlynn.com
injector:
  enabled: true
