global:
  enabled: true

server:

  affinity: ""

  ha:
    enabled: true

    raft:
      enabled: true
      setNodeId: true
      config: |
        storage "raft" {
          path = "/vault/data"
        }

        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_disable = "true"
        }
        service_registration "kubernetes" {}

injector:
  enabled: true
