{{- if .Values.clusterIssuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
  labels:
    app: {{ include "infra.name" . }}
    chart: {{ include "infra.chart" . }}
spec:
  acme:
    server: {{ .Values.clusterIssuer.acme.server }}
    email: {{ .Values.clusterIssuer.acme.email }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.acme.privateKeySecretName }}
    solvers:
    - http01:
        ingress:
          class: {{ .Values.clusterIssuer.acme.ingressClass }}
{{- end }}
